/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adj.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Teacher service. Represents a row in the &quot;SC_Teacher&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adj.model.impl.TeacherModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adj.model.impl.TeacherImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Teacher
 * @generated
 */
@ProviderType
public interface TeacherModel
	extends BaseModel<Teacher>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a teacher model instance should use the {@link Teacher} interface instead.
	 */

	/**
	 * Returns the primary key of this teacher.
	 *
	 * @return the primary key of this teacher
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this teacher.
	 *
	 * @param primaryKey the primary key of this teacher
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this teacher.
	 *
	 * @return the uuid of this teacher
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this teacher.
	 *
	 * @param uuid the uuid of this teacher
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the teacher ID of this teacher.
	 *
	 * @return the teacher ID of this teacher
	 */
	public long getTeacherId();

	/**
	 * Sets the teacher ID of this teacher.
	 *
	 * @param teacherId the teacher ID of this teacher
	 */
	public void setTeacherId(long teacherId);

	/**
	 * Returns the group ID of this teacher.
	 *
	 * @return the group ID of this teacher
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this teacher.
	 *
	 * @param groupId the group ID of this teacher
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this teacher.
	 *
	 * @return the company ID of this teacher
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this teacher.
	 *
	 * @param companyId the company ID of this teacher
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this teacher.
	 *
	 * @return the user ID of this teacher
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this teacher.
	 *
	 * @param userId the user ID of this teacher
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this teacher.
	 *
	 * @return the user uuid of this teacher
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this teacher.
	 *
	 * @param userUuid the user uuid of this teacher
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this teacher.
	 *
	 * @return the user name of this teacher
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this teacher.
	 *
	 * @param userName the user name of this teacher
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this teacher.
	 *
	 * @return the create date of this teacher
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this teacher.
	 *
	 * @param createDate the create date of this teacher
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this teacher.
	 *
	 * @return the modified date of this teacher
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this teacher.
	 *
	 * @param modifiedDate the modified date of this teacher
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this teacher.
	 *
	 * @return the name of this teacher
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this teacher.
	 *
	 * @param name the name of this teacher
	 */
	public void setName(String name);

	/**
	 * Returns the department of this teacher.
	 *
	 * @return the department of this teacher
	 */
	@AutoEscape
	public String getDepartment();

	/**
	 * Sets the department of this teacher.
	 *
	 * @param department the department of this teacher
	 */
	public void setDepartment(String department);

	/**
	 * Returns the age of this teacher.
	 *
	 * @return the age of this teacher
	 */
	public int getAge();

	/**
	 * Sets the age of this teacher.
	 *
	 * @param age the age of this teacher
	 */
	public void setAge(int age);

	/**
	 * Returns the salary of this teacher.
	 *
	 * @return the salary of this teacher
	 */
	public long getSalary();

	/**
	 * Sets the salary of this teacher.
	 *
	 * @param salary the salary of this teacher
	 */
	public void setSalary(long salary);

	/**
	 * Returns the address of this teacher.
	 *
	 * @return the address of this teacher
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this teacher.
	 *
	 * @param address the address of this teacher
	 */
	public void setAddress(String address);

	@Override
	public Teacher cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}